name: Crystal Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
            
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6

    - name: Install crystal
      uses: oprypin/install-crystal@v1
      with:
        crystal: 0.35.1

    - name: Build dependencies
      run: shards install
    
    - name: Tests
      run: crystal spec

    - name: Lint
      run: crystal tool format --check